# Generated by Django 2.2.5 on 2019-09-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(unique=True, verbose_name='res_id')),
                ('details', models.TextField(verbose_name='Json Data')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Restaurent', to_field='res_id')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User', to_field='username')),
            ],
        ),
    ]
