# Generated by Django 2.2.5 on 2019-09-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190929_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='username',
            new_name='user',
        ),
    ]
