# Generated by Django 2.2.5 on 2019-09-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_booking_restaurent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1, verbose_name='guests'),
        ),
    ]
